using Microsoft.Extensions.Options;

namespace Agentwerke.Agents.Models;

/// <summary>
/// Deterministic, zero-cost <see cref="ILanguageModelClient"/> for tokenless demos and CI
/// (issue #151). Selected via <c>Anthropic:Provider=mock</c>. Produces a stable, task-aware
/// text response so full workflows run end to end without an API key — and, when the agent has
/// a writable tool available (e.g. <c>sandbox.file_write</c>), invokes it once so tool-using
/// steps exercise the real Tool Gateway path deterministically.
/// </summary>
public sealed class MockLanguageModelClient : ILanguageModelClient
{
    private const string MockModelId = "autofac-mock-1";

    private readonly LanguageModelOptions _options;

    public MockLanguageModelClient(IOptions<LanguageModelOptions> options)
    {
        _options = options.Value;
    }

    public async Task<LanguageModelResponse> RunAsync(
        LanguageModelRequest request,
        Func<LanguageModelToolCall, CancellationToken, Task<LanguageModelToolResult>> toolExecutor,
        CancellationToken cancellationToken)
    {
        var toolCalls = new List<LanguageModelToolCall>();

        // If a writable tool is offered, call it once so tool-using steps produce a real,
        // deterministic side effect through the Tool Gateway (no model cost).
        var writeTool = request.Tools.FirstOrDefault(IsWritableTool);
        if (writeTool is not null)
        {
            var call = new LanguageModelToolCall(
                Id: "mock-tool-1",
                Name: writeTool.Name,
                Input: BuildMockToolInput(writeTool));
            toolCalls.Add(call);
            await toolExecutor(call, cancellationToken);
        }

        var output = BuildDeterministicOutput(request, writeTool);

        return new LanguageModelResponse(
            Succeeded: true,
            Output: output,
            FailureReason: null,
            AllToolCalls: toolCalls,
            Usage: new LanguageModelTokenUsage(0, 0),
            ModelId: MockModelId);
    }

    private static bool IsWritableTool(LanguageModelToolDefinition tool) =>
        tool.Name.Contains("file_write", StringComparison.OrdinalIgnoreCase)
        || tool.Name.Contains("file_edit", StringComparison.OrdinalIgnoreCase);

    private static IReadOnlyDictionary<string, string> BuildMockToolInput(LanguageModelToolDefinition tool)
    {
        // Provide best-effort values for the tool's declared parameters.
        var input = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var p in tool.Parameters)
        {
            input[p.Name] = p.Name.ToLowerInvariant() switch
            {
                "path" => "AUTOFAC_MOCK.md",
                "content" => "Generated by the Autofac mock model provider.\n",
                "message" => "chore: mock model output",
                _ => "mock"
            };
        }

        return input;
    }

    private static string BuildDeterministicOutput(LanguageModelRequest request, LanguageModelToolDefinition? writeTool)
    {
        var note = writeTool is null
            ? "No writable tool was offered; returned a text result only."
            : $"Invoked tool '{writeTool.Name}' once.";

        return $"""
            [autofac-mock] Task acknowledged and completed deterministically (no model tokens used).

            {note}

            This output is produced by the mock language-model provider
            (Anthropic:Provider=mock) for tokenless demos and CI.
            """;
    }
}
