apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "autofac.fullname" . }}-sandbox-executor
  namespace: {{ .Values.sandbox.namespace }}
  labels:
    {{- include "autofac.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "autofac.fullname" . }}-sandbox-executor
subjects:
  - kind: ServiceAccount
    name: {{ include "autofac.fullname" . }}-worker
    namespace: {{ .Release.Namespace }}
