apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autofac.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "autofac.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
