model_list:
  - model_name: glm-5.2
    litellm_params:
      model: nvidia_nim/z-ai/glm-5.2
      api_base: https://integrate.api.nvidia.com/v1
      api_key: os.environ/NVIDIA_API_KEY
  - model_name: llama-3.1-8b-instruct
    litellm_params:
      model: nvidia_nim/meta/llama-3.1-8b-instruct
      api_base: https://integrate.api.nvidia.com/v1
      api_key: os.environ/NVIDIA_API_KEY
  - model_name: nemotron-mini-4b-instruct
    litellm_params:
      model: nvidia_nim/nvidia/nemotron-mini-4b-instruct
      api_base: https://integrate.api.nvidia.com/v1
      api_key: os.environ/NVIDIA_API_KEY

  - model_name: llama-3.3-70b-instruct
    litellm_params:
      model: nvidia_nim/meta/llama-3.3-70b-instruct
      api_base: https://integrate.api.nvidia.com/v1
      api_key: os.environ/NVIDIA_API_KEY
  - model_name: qwen3-next-80b
    litellm_params:
      model: nvidia_nim/qwen/qwen3-next-80b-a3b-instruct
      api_base: https://integrate.api.nvidia.com/v1
      api_key: os.environ/NVIDIA_API_KEY
  - model_name: deepseek-v4-pro
    litellm_params:
      model: nvidia_nim/deepseek-ai/deepseek-v4-pro
      api_base: https://integrate.api.nvidia.com/v1
      api_key: os.environ/NVIDIA_API_KEY

litellm_settings:
  drop_params: true
  set_verbose: false
