{{- if .Values.sandbox.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.sandbox.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    autofac.io/purpose: sandbox-execution
{{- end }}
