import type { ApprovalRequest, TemplateDetail, TemplateSummary, Workflow, WorkflowRun } from '../types';

export const workflowsFixture: Workflow[] = [
  {
    id: 'wf-001',
    name: 'GitHub PR Review',
    description: 'Automated review workflow',
    version: 'v2.3.1',
    status: 'active',
    owner: 'platform-eng',
    createdAt: new Date(Date.now() - 500000).toISOString(),
    lastEditedAt: new Date(Date.now() - 200000).toISOString(),
    validationState: 'valid',
    tags: ['github'],
  },
  {
    id: 'wf-002',
    name: 'Dependency Patch',
    description: 'Dependency remediation',
    version: 'v1.0.4',
    status: 'active',
    owner: 'secops',
    createdAt: new Date(Date.now() - 900000).toISOString(),
    lastEditedAt: new Date(Date.now() - 300000).toISOString(),
    validationState: 'valid',
    tags: ['security'],
  },
];

export const runsFixture: WorkflowRun[] = [
  {
    id: 'run-0421',
    workflowId: 'wf-001',
    workflowName: 'GitHub PR Review',
    workflowVersion: 'v2.3.1',
    status: 'awaiting_approval',
    riskLevel: 'high',
    currentStep: 'Merge to main',
    requestedBy: 'alice@example.com',
    startedAt: new Date(Date.now() - 8 * 60_000).toISOString(),
    durationMs: 8 * 60_000,
    pendingApprovals: 1,
    tags: ['production'],
    steps: [
      {
        id: 'step-1',
        name: 'Trigger',
        type: 'start_event',
        status: 'completed',
      },
      {
        id: 'step-2',
        name: 'Merge to main',
        type: 'user_task',
        status: 'awaiting_approval',
        output: 'Specification generated successfully.',
        policyDecision: {
          kind: 'escalate',
          policyId: 'pol-prod-merge',
          policyName: 'Production Merge Protection',
          rationale: 'Requires human approval.',
          riskScore: 72,
          riskLevel: 'high',
          riskFactors: ['production'],
          decidedAt: new Date().toISOString(),
        },
        runtimeSnapshot: {
          agentName: 'spec-writer',
          action: 'spec.generate',
          executionMode: 'agent_sandboxed',
          promptInline: 'Write a concise technical specification.',
          skills: [],
          tools: [],
          toolInvocations: [],
          mcpServers: [],
          hooks: [],
          permissionLevel: 'read-write',
          allowedTools: ['sandbox.execute'],
          deniedTools: [],
          subAgentsEnabled: false,
          stepArtifacts: [
            {
              name: 'spec.md',
              uri: '/api/runs/run-0421/artifacts/spec.md',
              contentType: 'text/markdown',
            },
          ],
          sandboxExecution: {
            provider: 'opensandbox',
            sandboxId: 'sbx-42',
            commandState: 'Completed',
            exitCode: 0,
            durationMs: 1388,
            logs: [
              {
                stream: 'stdout',
                message: 'spec generation running',
                timestamp: new Date(Date.now() - 90_000).toISOString(),
              },
              {
                stream: 'stdout',
                message: 'spec generation completed',
                timestamp: new Date(Date.now() - 89_000).toISOString(),
              },
            ],
            diagnostics: {
              provider: 'opensandbox',
              'sandbox.state': 'Running',
              'execd.run.request_id': 'run-req-123',
            },
          },
          tokenUsage: {
            inputTokens: 412,
            outputTokens: 198,
            modelId: 'claude-sonnet-4-6',
            elapsedMs: 2140,
          },
        },
      },
    ],
    events: [
      {
        id: 'evt-a',
        type: 'retry_scheduled',
        message: 'Retry scheduled after transient failure.',
        createdAt: new Date(Date.now() - 6 * 60_000).toISOString(),
      },
      {
        id: 'evt-b',
        type: 'timeout_triggered',
        message: 'Timeout boundary triggered on security scan.',
        createdAt: new Date(Date.now() - 5 * 60_000).toISOString(),
      },
    ],
    artifacts: [
      {
        name: 'scan-report.json',
        sizeBytes: 2048,
        lastModifiedAt: new Date(Date.now() - 4 * 60_000).toISOString(),
      },
    ],
    approvals: [
      {
        id: 'apr-1001',
        runId: 'run-0421',
        workflowName: 'GitHub PR Review',
        actionRequested: 'Merge branch feature/auth-refactor to main',
        requester: 'alice@example.com',
        agentName: 'GitAgent',
        policyRationale: 'Policy requires review.',
        riskScore: 72,
        riskLevel: 'high',
        riskFactors: ['production'],
        affectedSystems: ['production/api'],
        slaDeadline: new Date(Date.now() + 60 * 60_000).toISOString(),
        createdAt: new Date(Date.now() - 6 * 60_000).toISOString(),
        status: 'pending',
        priority: 'high',
      },
    ],
    },
  {
    id: 'run-0420',
    workflowId: 'wf-002',
    workflowName: 'Dependency Patch',
    workflowVersion: 'v1.0.4',
    status: 'running',
    riskLevel: 'medium',
    currentStep: 'Patch dependencies',
    requestedBy: 'bot@autofac',
    startedAt: new Date(Date.now() - 22 * 60_000).toISOString(),
    durationMs: 22 * 60_000,
    pendingApprovals: 0,
    tags: ['security'],
  },
];

export const approvalsFixture: ApprovalRequest[] = [
  {
    id: 'apr-1001',
    runId: 'run-0421',
    workflowName: 'GitHub PR Review',
    actionRequested: 'Merge branch feature/auth-refactor to main',
    requester: 'alice@example.com',
    agentName: 'GitAgent',
    policyRationale: 'Policy requires review.',
    riskScore: 72,
    riskLevel: 'high',
    riskFactors: ['production'],
    affectedSystems: ['production/api'],
    slaDeadline: new Date(Date.now() + 60 * 60_000).toISOString(),
    createdAt: new Date(Date.now() - 6 * 60_000).toISOString(),
    status: 'pending',
    priority: 'high',
  },
  {
    id: 'apr-1002',
    runId: 'run-0419',
    workflowName: 'Incident Recovery',
    actionRequested: 'Approve rollback for failed deploy',
    requester: 'ops@example.com',
    agentName: 'ReleaseAgent',
    policyRationale: 'Rollback touched production scope.',
    riskScore: 55,
    riskLevel: 'medium',
    riskFactors: ['production'],
    affectedSystems: ['production/web'],
    slaDeadline: new Date(Date.now() - 30 * 60_000).toISOString(),
    createdAt: new Date(Date.now() - 90 * 60_000).toISOString(),
    status: 'approved',
    priority: 'normal',
    decisionComment: 'Rollback approved after review.',
    decidedAt: new Date(Date.now() - 20 * 60_000).toISOString(),
    decidedBy: 'reviewer@example.com',
  },
];

export const artifactApprovalFixture: ApprovalRequest = {
  id: 'apr-2001',
  runId: 'run-0430',
  workflowName: 'Requirement Design',
  actionRequested: 'requirement-design',
  requester: 'bob@example.com',
  agentName: 'business-analyst',
  policyRationale: 'Doc-generation gate.',
  riskScore: 18,
  riskLevel: 'low',
  riskFactors: [],
  affectedSystems: [],
  slaDeadline: new Date(Date.now() + 120 * 60_000).toISOString(),
  createdAt: new Date(Date.now() - 4 * 60_000).toISOString(),
  status: 'pending',
  priority: 'normal',
  artifactName: 'requirements.md',
};

export const templatesFixture: TemplateSummary[] = [
  {
    id: 'tmpl-prod-deploy',
    name: 'Production Deploy',
    description: 'Ship a reviewed change to production with a release manager sign-off.',
    trigger: 'github_pr_merged',
    policyLevel: 'elevated',
    tags: ['github'],
    agentRoles: ['build-agent'],
    approvalRoles: ['release-manager'],
  },
];

export const templateDetailFixture: TemplateDetail = {
  ...templatesFixture[0],
  requiredInputs: ['releaseVersion'],
  evidenceExpectations: ['changelog'],
  bpmnXml:
    '<?xml version="1.0" encoding="UTF-8"?><bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL"><bpmn:process id="ProductionDeployFlow" name="Production Deploy"><bpmn:startEvent id="Start" /><bpmn:endEvent id="End" /></bpmn:process></bpmn:definitions>',
};
